default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: arbitrage_vasya_test
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: arbitrage_vasya_test
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['PRODUCTION_DATABASE_URL'] %>
